export const HOME_CASUAL = 'home_casual';  // 首页轮播图
export const HOME_NAV = 'home_nav';  // 首页导航
export const HOME_SHOP_LIST = 'home_shop_list';  // 首页商品列表
export const REC_SHOP_LIST = 'rec_shop_list';  // 推荐商品列表
export const SEARCH_GOODS = 'search_goods';  // 搜索列表
export const USER_INFO = 'user_info';  // 同步用户的数据
export const RESET_USER_INFO = 'reset_user_info';  // 清空用户的数据
export const ADD_GOODS_COUNT = 'add_goods_count';  // 增加 购物车商品的数量
export const REDUCE_GOODS_COUNT = 'reduce_goods_count';  // 减少 购物车商品的数量
export const SELECTED_SINGER_GOODS = 'selected_singer_goods';  // 单个商品的选中和取消选中
export const SELECTED_ALL_GOODS = 'selected_all_goods';  // 是否全选
export const DEL_SINGER_GOODS = 'del_singer_goods';  // 删除单个商品
